[package]
name = "cita-vm"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3"
evm = { path="./evm" }
state = { path="./state" }
cita_trie = { git = "https://github.com/cryptape/cita-trie.git", branch = "master" }
parity-rocksdb = "0.5.0"
lru-cache = "0.1.1"

[workspace]
members = [
    "evm",
    "ewasm",
    "state"
]
